<?php
return [
    "$npcname has a habit of speaking in riddles or vague phrases, rarely giving a straightforward answer, leaving listeners puzzled or intrigued.",
    "$npcname constantly assesses the value of objects or situations, muttering things like 'worth a handful of septims' or 'barely worth a second glance.'",
    "$npcname often boasts of past deeds, embellishing stories to seem larger-than-life, whether its about defeating bandits or outrunning a pack of wolves.",
    "$npcname uses overly formal or flowery language, regardless of the situation, giving the impression theyre more important than they might actually be.",
    "$npcname startles easily, overreacting to minor surprises and making dramatic exclamations even when the situation is harmless.",
    "$npcname frequently mentions their love of drink, often wishing they could be drinking rather then whatever they are doing right now.",
    "$npcname keeps their sentences brief and to the point, constantly scanning their surroundings as though expecting trouble to appear at any moment.",
    "$npcname peppers conversations with religious sayings or blessings, pausing at random to mutter prayers or invoke divine guidance.",
    "$npcname laughs loudly and at odd moments, their mirth sometimes inappropriate and unsettling to those around them.",
    "$npcname enjoys recounting old tales or bits of local history, often veering off into tangents about events or people from the past.",
    "$npcname refuses to back down in any argument, no matter how small or insignificant, stubbornly clinging to their point of view.",
    "$npcname insists on challenging anyone who questions their honor, even if the slight is minor or unintended, seeing every disagreement as a personal affront.",
    "$npcname occasionally mutters strange combinations of words or phrases, as though rehearsing something, leaving an air of mystery about their knowledge.",
    "$npcname cracks jokes and tries to lighten the mood, though their attempts at humor sometimes feel misplaced or poorly timed.",
    "$npcname constantly uses idioms and proverbs, even in situations where they make little sense, leaving others scratching their heads.",
    "$npcname has a habit of over-apologizing for even the smallest inconveniences, often stumbling over their words to avoid conflict.",
    "$npcname repeats the words of others, they do this without realizing it.",
    "$npcname derails conversations frequently with irrelevant observations, like commenting on the weather or how their boots are wearing out.",
    "$npcname avoids directly answering questions, instead responding with questions of their own or deflecting with vague statements.",
    "$npcname greets everyone they meet with an overly cheerful tone, regardless of the situation, sometimes to the annoyance of others.",
    "$npcname has a habit of over-explaining simple concepts, as though assuming others cant understand without detailed clarification.",
    "$npcname hesitates before speaking, often starting sentences over or leaving thoughts unfinished, as if unsure of what to say.",
    "$npcname insists on using nicknames for everyone they meet, even if the person prefers to be addressed more formally.",
    "$npcname takes every compliment as a personal challenge, feeling the need to outdo themselves or prove they deserve the praise.",
    "$npcname frequently comments on how things 'used to be better' in the past, regardless of whether theyve actually experienced those times.",
    "$npcname carries a peculiar fixation on fairness, pointing out perceived injustices or unfair treatment in even trivial matters.",
    "$npcname refers to themselves in the third person, making their speech stand out as eccentric or self-important.",
    "$npcname seems overly curious, asking far too many questions about others lives, sometimes venturing into topics considered personal or taboo.",
    "$npcname speaks sparingly, relying on gestures or brief comments to communicate, making their few words carry extra weight."
];
