<?php
//No longer used, is in the database
return [
    "$npcname has a habit of speaking in riddles or vague phrases, rarely giving a straightforward answer, leaving listeners puzzled or intrigued.",
    "$npcname constantly assesses the value of objects or situations, muttering things like 'worth a handful of septims' or 'barely worth a second glance.'",
    "$npcname often boasts of past deeds, embellishing stories to seem larger-than-life, whether its about defeating bandits or outrunning a pack of wolves.",
    "$npcname uses overly formal or flowery language, regardless of the situation, giving the impression theyre more important than they might actually be.",
    "$npcname startles easily, overreacting to minor surprises and making dramatic exclamations even when the situation is harmless.",
    "$npcname frequently mentions their love of drink, often wishing they could be drinking rather then whatever they are doing right now.",
    "$npcname keeps their sentences brief and to the point, constantly scanning their surroundings as though expecting trouble to appear at any moment.",
    "$npcname peppers conversations with religious sayings or blessings, pausing at random to mutter prayers or invoke divine guidance.",
    "$npcname laughs loudly and at odd moments, their mirth sometimes inappropriate and unsettling to those around them.",
    "$npcname enjoys recounting old tales or bits of local history, often veering off into tangents about events or people from the past.",
    "$npcname refuses to back down in any argument, no matter how small or insignificant, stubbornly clinging to their point of view.",
    "$npcname insists on challenging anyone who questions their honor, even if the slight is minor or unintended, seeing every disagreement as a personal affront.",
    "$npcname occasionally mutters strange combinations of words or phrases, as though rehearsing something, leaving an air of mystery about their knowledge.",
    "$npcname cracks jokes and tries to lighten the mood, though their attempts at humor sometimes feel misplaced or poorly timed.",
    "$npcname constantly uses idioms and proverbs, even in situations where they make little sense, leaving others scratching their heads.",
    "$npcname has a habit of over-apologizing for even the smallest inconveniences, often stumbling over their words to avoid conflict.",
    "$npcname repeats the words of others, they do this without realizing it.",
    "$npcname avoids directly answering questions, instead responding with questions of their own or deflecting with vague statements.",
    "$npcname greets everyone they meet with an overly cheerful tone, regardless of the situation, sometimes to the annoyance of others.",
    "$npcname has a habit of over-explaining simple concepts, as though assuming others cant understand without detailed clarification.",
    "$npcname hesitates before speaking, often starting sentences over or leaving thoughts unfinished, as if unsure of what to say.",
    "$npcname insists on using nicknames for everyone they meet, even if the person prefers to be addressed more formally.",
    "$npcname takes every compliment as a personal challenge, feeling the need to outdo themselves or prove they deserve the praise.",
    "$npcname frequently comments on how things 'used to be better' in the past, regardless of whether theyve actually experienced those times.",
    "$npcname carries a peculiar fixation on fairness, pointing out perceived injustices or unfair treatment in even trivial matters.",
    "$npcname refers to themselves in the third person, making their speech stand out as eccentric or self-important.",
    "$npcname seems overly curious, asking far too many questions about others lives, sometimes venturing into topics considered personal or taboo.",
    "$npcname speaks sparingly, relying on gestures or brief comments to communicate, making their few words carry extra weight.",
    "$npcname constantly mentions the weather, relating it to omens or signs from the divines about what might happen next.",
    "$npcname frequently clears their throat before speaking, as if always preparing to make an important announcement.",
    "$npcname has a habit of touching their weapons or armor while speaking, a nervous tic that suggests they're always ready for trouble.",
    "$npcname speaks with an unusual cadence, emphasizing random words in their sentences for no apparent reason.",
    "$npcname compares everything to hunting or fishing, using metaphors like 'quick as a slaughterfish' or 'stubborn as a horker'.",
    "$npcname interrupts themselves mid-sentence to comment on seemingly unrelated observations about their surroundings.",
    "$npcname occasionally whispers parts of sentences, as if sharing secrets even when discussing mundane topics.",
    "$npcname sighs dramatically before responding to questions, as though the weight of the world rests on their shoulders.",
    "$npcname frequently mentions their aches and pains, blaming old wounds or the changing seasons for their discomfort.",
    "$npcname has a peculiar habit of sniffing the air while conversing, sometimes commenting on scents others can't detect.",
    "$npcname speaks with excessive politeness to those of higher status, but becomes notably curt with those they deem beneath them.",
    "$npcname prides themselves on their knowledge of herbs and potions, offering unsolicited advice about remedies for ailments no one mentioned.",
    "$npcname constantly fidgets with a trinket or keepsake while speaking, seeming distracted but actually listening intently.",
    "$npcname makes melodramatic predictions about doom and misfortune, seeing bad omens in the most ordinary occurrences.",
    "$npcname speaks with unusual precision about measurements and numbers, insisting on exact details even when approximations would suffice.",
    "$npcname frequently references their dreams as though they were prophecies, interpreting them as guidance for daily decisions.",
    "$npcname begins many sentences with 'My mother always said...' followed by folk wisdom that may or may not be relevant.",
    "$npcname habitually exaggerates the dangers of everyday situations, warning of unlikely disasters with complete conviction.",
    "$npcname speaks with a hint of suspicion toward strangers, often implying hidden motives behind innocent questions.",
    "$npcname is oddly preoccupied with social status, frequently mentioning their connections to minor nobles or local officials.",
    "$npcname punctuates their speech with unusual hand gestures that seem to have personal significance but confuse others.",
    "$npcname consistently underplays serious situations, responding to danger or urgency with casual indifference.",
    "$npcname relates most conversations back to their homeland or childhood, often beginning stories with 'Where I come from...'",
    "$npcname speaks with excessive volume, as if everyone around them is hard of hearing, drawing unwanted attention.",
    "$npcname has a habit of trailing off mid-thought when distracted by something mundane, like a passing bird or change in lighting.",
    "$npcname frequently misquotes famous sayings or legends, combining different stories into confused but confident assertions.",
    "$npcname obsessively counts things while talking - steps taken, people present, items on a shelf - sometimes losing track of the conversation.",
    "$npcname speaks with flowery compliments to everyone, their excessive flattery making even simple interactions feel theatrical.",
    "$npcname frequently mentions encounters with Daedra or supernatural beings, though the details change with each telling.",
    "$npcname has developed a peculiar way of avoiding certain common words, substituting unusual alternatives that sound oddly formal.",
    "$npcname randomly breaks into snippets of song mid-conversation, often folk tunes that relate vaguely to the topic at hand.",
    "$npcname speaks with dramatic pauses between phrases, as if expecting applause or reaction after each statement.",
    "$npcname habitually turns statements into questions, ending sentences with 'wouldn't you agree?' or 'don't you think so?'",
    "$npcname insists on correcting minor inaccuracies in others' statements, interrupting the flow of conversation for pedantic details.",
    "$npcname speaks fondly of animals they've known, often claiming to understand what creatures are thinking or feeling.",
    "$npcname frequently references constellations and star signs, attributing personality traits or daily fortunes to celestial influences.",
    "$npcname has a tendency to speak in unnecessarily complex sentences, using three words where one would suffice.",
    "$npcname often mentions food in their metaphors and expressions, describing emotions and situations in terms of flavors and meals.",
    "$npcname habitually expresses disbelief at ordinary information, responding with 'Truly?' or 'Is that so?' to even mundane statements.",
    "$npcname occasionally adopts different accents or speech patterns, as if momentarily becoming someone else before returning to normal.",
    "$npcname speaks with nostalgic reverence about the 'old ways' of doing things, lamenting how traditions are being forgotten.",
    "$npcname repeatedly mentions their sensitivity to magic, claiming to feel spells and enchantments that others cannot perceive.",
    "$npcname habitually invents elaborate backstories for everyday objects, treating mundane items as if they have epic histories.",
    "$npcname has an unusual fascination with the time of day, frequently checking the position of the sun and commenting on its significance.",
    "$npcname speaks with excessive caution about certain topics, lowering their voice and glancing around as if being watched.",
    "$npcname frequently uses analogies related to their profession or skills, even when speaking to those unfamiliar with the terminology.",
    "$npcname has a habit of finishing others' sentences, often incorrectly but with complete confidence in their assumption.",
    "$npcname occasionally slips into referring to themselves as 'we' instead of 'I', leaving listeners unsure if they speak for a group.",
    "$npcname speaks with rhythmic patterns, unconsciously tapping their fingers or feet as they talk, as if keeping time to music only they hear.",
    "$npcname habitually begins responses with 'Well, actually...' before correcting or contradicting what was just said.",
    "$npcname has an odd tendency to personify inanimate objects, speaking about weapons, tools, or furniture as if they have personalities.",
    "$npcname frequently makes obscure historical references that few understand, then seems disappointed when others don't recognize them.",
    "$npcname speaks with unusual euphemisms for common things, referring to death, money, or danger in colorful but indirect terms.",
    "$npcname has a superstitious habit of knocking on wood or making protective gestures when certain topics are mentioned.",
    "$npcname occasionally becomes distracted mid-sentence by their own reflection in any shiny surface, losing their train of thought.",
    "$npcname habitually addresses invisible entities, briefly nodding or murmuring to empty spaces before continuing conversations normally.",
    "$npcname speaks with peculiar emphasis on certain syllables, giving their speech a distinctive rhythm that others find memorable.",
    "$npcname frequently offers unwanted advice based on their interpretation of the listener's aura or energy, which they claim to perceive.",
    "$npcname has developed a habit of categorizing people they meet by comparing them to different types of creatures or elements.",
    "$npcname unconsciously mimics the posture and gestures of whoever they're speaking with, creating an odd mirror effect during conversations.",
    "$npcname often speculates about alternate paths their life might have taken, briefly role-playing these other selves during normal dialogue.",
    "$npcname speaks with particular fondness about a specific region or city, somehow relating most topics back to this favored place.",
    "$npcname has a tendency to narrate their own actions in quiet asides, as if providing commentary on their own behavior.",
    "$npcname frequently mentions premonitions or hunches that guide their decisions, treating these feelings as more reliable than facts.",
    "$npcname habitually collects small, seemingly worthless objects, often pausing conversations to pocket an interesting stone or leaf.",
    "$npcname speaks with theatrical voices when quoting or impersonating others, dramatically changing their tone and mannerisms.",
    "$npcname has developed elaborate personal theories about common natural phenomena, explaining rain or wind with confident but bizarre logic.",
    "$npcname occasionally lapses into the distinctive dialect of their childhood region, especially when emotional or surprised.",
    "$npcname punctuates their speech with a distinctive laugh or sound that has become their unintentional signature.",
    "$npcname speaks reverently about a particular skill or craft, evaluating people primarily by their proficiency in this valued ability.",
    "$npcname habitually exaggerates distances and measurements, describing short walks as 'leagues away' or small objects as 'massive'."
];
