<?php
/*
 Request creation and player_request overriding
*/

$sk_date = convert_gamets2skyrim_date($gameRequest[2]); //skyrim date 

if ($gameRequest[0] == "funcret") { // Take out the functions part

	$returnFunction = explode("@", $gameRequest[3]); // Function returns here
	$functionCodeName=$returnFunction[1];
		
	//$request = str_replace("call function if needed,", "continue chat as $HERIKA_NAME,", $PROMPTS["inputtext"][0]); 
	if (isset($PROMPTS["afterfunc"]["cue"][$functionCodeName])) {
		$request =$PROMPTS["afterfunc"]["cue"][$functionCodeName];
	
	} else 
		$request =$PROMPTS["afterfunc"]["cue"]["default"];
	
	/*
	Functions of which return value is provided by server
	$returnFunction is in the form command@function codename@function parameter@result
	So here we will override the result (which probably will be nothing)
	*/
	
	if ($functionCodeName == "Attack") {
		if (strpos($returnFunction[3],"Error")!==false) {
			$GLOBALS["FUNCTIONS_ARE_ENABLED"]=false;	// RE-Enable functions	// Endless loop if enabled
			$request="Specify a valid target:(available targets: ".implode(",",$GLOBALS["FUNCTION_PARM_INSPECT"]).")";	
			Logger::info("Request function again {$returnFunction[3]}");
		}
		
	} else {
		if (isset($GLOBALS["FUNCSERV"][$functionCodeName])) {
			call_user_func_array($GLOBALS["FUNCSERV"][$functionCodeName],[]);
		}
		
	}
	
} else if ($gameRequest[0] == "chatnf_book") { // Takea out the functions part
    // Load book prompt from database with fallback to hardcoded version
    $bookPrompt = null;
    try {
        $promptData = $db->fetchOne("SELECT custom_prompt, default_prompt FROM prompts WHERE prompt_key = 'book_summary_prompt'");
        if ($promptData) {
            // Use custom_prompt if set, otherwise use default_prompt
            $bookPrompt = (!empty($promptData['custom_prompt'])) ? $promptData['custom_prompt'] : $promptData['default_prompt'];
            Logger::info("[BOOK] Loaded prompt from database <$bookPrompt> (custom: " . (!empty($promptData['custom_prompt']) ? 'yes' : 'no') . ")");
        }
    } catch (Exception $e) {
        Logger::warn("[BOOK] Failed to load prompt from database, using hardcoded fallback: " . $e->getMessage());
    }
    
    // Hardcoded fallback if database query failed or returned no results
    if (!$bookPrompt) {
        $bookPrompt = selectRandomInArray($PROMPTS["book"]["cue"]);
        Logger::info("[BOOK] Using hardcoded fallback prompt");
    }
    
    $request = $bookPrompt;
    $books=$db->fetchAll("select title from books where title is not null order by gamets desc");
    // Override player request here. This request is generated by dll plugin, in english.
    $gameRequest[3]=$PROMPTS["book"]["player_request"][0]."<".$books[0]["title"].">";	
    $request = make_replacements_bracketed($gameRequest[3]." $bookPrompt");
	
	
} else if ($gameRequest[0] == "memory") {
	
	$memoriesFound=queryMemory($gameRequest[3],null,$GLOBALS["HERIKA_NAME"]);
	$GLOBALS["DEBUG_DATA"]["memories"]["selected"]=current($memoriesFound["content"]);
	$GLOBALS["MEMORY_INJECTION_RESULT"]=$GLOBALS["DEBUG_DATA"]["memories"]["selected"]["briefing"];
	
	$request=strtr(selectRandomInArray($PROMPTS[$gameRequest[0]]["cue"]),["#MEMORY_INJECTION_RESULT#"=>$GLOBALS["MEMORY_INJECTION_RESULT"]]);
	
	
} else if ($gameRequest[0] == "diary") {
	// Check if this is a narrator diary request and if narrator diary is disabled
	if (isset($GLOBALS["HERIKA_NAME"]) && $GLOBALS["HERIKA_NAME"] === "The Narrator") {
		if (!isset($GLOBALS["NARRATOR_DIARY_ENABLED"]) || !$GLOBALS["NARRATOR_DIARY_ENABLED"]) {
			Logger::info("[DIARY] Narrator diary is disabled, skipping");
			die();
		}
	}
	
	// Use configurable DIARY_PROMPT or fallback to default
	$diaryCharacterName = function_exists('chimGetPromptCharacterName')
		? chimGetPromptCharacterName()
		: $GLOBALS["HERIKA_NAME"];
	$diaryPrompt = isset($GLOBALS["DIARY_PROMPT"]) && !empty($GLOBALS["DIARY_PROMPT"]) 
		? strtr($GLOBALS["DIARY_PROMPT"],['{$GLOBALS["HERIKA_NAME"]}'=>$diaryCharacterName,'{$GLOBALS["PLAYER_NAME"]}'=>$GLOBALS["PLAYER_NAME"],'#HERIKA_NAME#'=>$diaryCharacterName,'#NARRATOR_NAME#'=>function_exists('chimGetNarratorRoleplayName') ? chimGetNarratorRoleplayName() : 'The Narrator','#PLAYER_NAME#'=>$GLOBALS["PLAYER_NAME"]])
		: "Please write a short summary of {$GLOBALS["PLAYER_NAME"]} and {$diaryCharacterName}s last dialogues and events written above into {$diaryCharacterName}s diary . WRITE AS IF YOU WERE {$diaryCharacterName}.";
	
	// Add current game date/time context to the prompt
	$diaryPrompt = "Current date and time: {$sk_date}. " . $diaryPrompt;
	
	$request = $diaryPrompt;
	
	logMemory($GLOBALS["PLAYER_NAME"], $GLOBALS["HERIKA_NAME"],
        "(Important note: Something important happened here for {$GLOBALS["PLAYER_NAME"]} on {$sk_date}. You should use the tag #PlotRelevantEvent)",
        $momentum, $gameRequest[2],'diary_intent',$gameRequest[1]);

} else if ($gameRequest[0] == "narrator_welcome") {
	// Handle narrator welcome message
	if (isset($PROMPTS["narrator_welcome"]["cue"]) && is_array($PROMPTS["narrator_welcome"]["cue"]) && count($PROMPTS["narrator_welcome"]["cue"]) > 0) {
		$request = selectRandomInArray($PROMPTS["narrator_welcome"]["cue"]);
	} else {
		Logger::error("[NARRATOR_WELCOME] Cue not found or empty in request.php!");
		$request = "Give a brief (2-3 sentence) recap of recent events and adventures. Welcome the player back to their journey.";
	}

} else if ($gameRequest[0] == "quest" || $gameRequest[0] == "narrator_quest_comment") {
	// Load quest comment prompt from database with fallback
	$questPromptText = null;
	try {
		$questPromptData = $db->fetchOne("SELECT custom_prompt, default_prompt FROM prompts WHERE prompt_key = 'quest_comment_prompt'");
		if ($questPromptData) {
			$questPromptText = (!empty($questPromptData['custom_prompt'])) 
				? $questPromptData['custom_prompt'] 
				: $questPromptData['default_prompt'];
		}
	} catch (Exception $e) {
		Logger::warn("[QUEST] Failed to load prompt from database: " . $e->getMessage());
	}
	
	// Hardcoded fallback
	if (!$questPromptText) {
		$questPromptText = "{$GLOBALS["HERIKA_NAME"]}, what should we do about this new quest?";
	}
	
	// Replace {HERIKA_NAME} placeholder if present
        $questPromptText = strtr($questPromptText, [
            '{HERIKA_NAME}' => function_exists('chimGetPromptCharacterName') ? chimGetPromptCharacterName() : $GLOBALS["HERIKA_NAME"],
            '{NARRATOR_NAME}' => function_exists('chimGetNarratorRoleplayName') ? chimGetNarratorRoleplayName() : 'The Narrator',
        ]);
	
	// Override the player_request in PROMPTS array
	$promptKey = $gameRequest[0];
	if (!isset($PROMPTS[$promptKey])) {
		$PROMPTS[$promptKey] = [];
	}
	$PROMPTS[$promptKey]["player_request"] = [$questPromptText];
	
	// Also set for "quest" key if this is narrator_quest_comment (for compatibility)
	if ($gameRequest[0] == "narrator_quest_comment") {
		if (!isset($PROMPTS["quest"])) {
			$PROMPTS["quest"] = [];
		}
		$PROMPTS["quest"]["player_request"] = [$questPromptText];
	}

} else {

	if ($gameRequest[0] == "instruction" || $gameRequest[0] == "suggestion") {
		// Override some descriptions when in instruction mode
		require_once(__DIR__."/../functions/functions_instruction.php");
	}

	
	if (isset($PROMPTS[$gameRequest[0]]["player_request"])) {
		$request = selectRandomInArray($PROMPTS[$gameRequest[0]]["cue"]); // Add support for arrays here	
		$playerRequestOptions = $PROMPTS[$gameRequest[0]]["player_request"];
		if (is_array($playerRequestOptions)) {
			$playerRequestOptions = array_values(array_filter($playerRequestOptions, static fn($item) => trim((string)$item) !== ""));
			if (count($playerRequestOptions) > 0) {
				$gameRequest[3]=selectRandomInArray($playerRequestOptions);	// Overwrite
			}
		}
		// error_log(__FILE__." ".__LINE__." $request {$gameRequest[3]}");
	}
	else {
		if (isset($PROMPTS[$gameRequest[0]]["cue"]))
			$request = selectRandomInArray($PROMPTS[$gameRequest[0]]["cue"]); // Add support for arrays here	
		else {
			Logger::warn("Request cue is empty! - ".$gameRequest[0]." - ".print_r($PROMPTS[$gameRequest[0]] ?? [],true)." - ".__FILE__.":".__LINE__);
			$request = "{$GLOBALS["TEMPLATE_DIALOG"]}";
		}
	}
}






$commandSent = false;

// Add
if (($gameRequest[0] == "inputtext") || ($gameRequest[0] == "inputtext_s") || (strpos($gameRequest[0],"chatnf")!==false)) {
	$gameRequest[3] = $gameRequest[3]." $DIALOGUE_TARGET";
}

?>
