CREATE TABLE public.oghma_catalogs (
    catalog_version text PRIMARY KEY,
    contract_version text NOT NULL,
    manifest_sha256 character(64) NOT NULL,
    articles_sha256 character(64) NOT NULL,
    row_count integer NOT NULL CHECK (row_count >= 0),
    state text NOT NULL CHECK (state IN ('inactive', 'active', 'superseded')),
    previous_catalog_version text REFERENCES public.oghma_catalogs(catalog_version),
    imported_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    activated_at timestamp with time zone,
    superseded_at timestamp with time zone,
    metadata jsonb NOT NULL DEFAULT '{}'::jsonb
);

CREATE UNIQUE INDEX oghma_catalogs_one_active
    ON public.oghma_catalogs ((state))
    WHERE state = 'active';

CREATE TABLE public.oghma_catalog_entries (
    catalog_version text NOT NULL REFERENCES public.oghma_catalogs(catalog_version) ON DELETE CASCADE,
    topic text NOT NULL,
    aliases text NOT NULL DEFAULT '',
    topic_desc text NOT NULL,
    knowledge_class text NOT NULL DEFAULT '',
    topic_desc_basic text NOT NULL DEFAULT '',
    knowledge_class_basic text NOT NULL DEFAULT '',
    tags text NOT NULL DEFAULT '',
    category text NOT NULL DEFAULT '',
    row_sha256 character(64) NOT NULL,
    PRIMARY KEY (catalog_version, topic)
);

CREATE FUNCTION public.oghma_catalog_entries_immutable() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
    RAISE EXCEPTION 'Oghma catalog entries are immutable';
END;
$$;

CREATE TRIGGER oghma_catalog_entries_immutable_trigger
BEFORE UPDATE OR DELETE ON public.oghma_catalog_entries
FOR EACH ROW EXECUTE FUNCTION public.oghma_catalog_entries_immutable();

CREATE FUNCTION public.oghma_catalog_identity_immutable() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
    IF TG_OP = 'DELETE' THEN
        RAISE EXCEPTION 'Oghma catalog snapshots are immutable';
    END IF;
    IF NEW.catalog_version IS DISTINCT FROM OLD.catalog_version
       OR NEW.contract_version IS DISTINCT FROM OLD.contract_version
       OR NEW.manifest_sha256 IS DISTINCT FROM OLD.manifest_sha256
       OR NEW.articles_sha256 IS DISTINCT FROM OLD.articles_sha256
       OR NEW.row_count IS DISTINCT FROM OLD.row_count
       OR NEW.metadata IS DISTINCT FROM OLD.metadata
       OR NEW.imported_at IS DISTINCT FROM OLD.imported_at THEN
        RAISE EXCEPTION 'Oghma catalog identity is immutable';
    END IF;
    RETURN NEW;
END;
$$;

CREATE TRIGGER oghma_catalog_identity_immutable_trigger
BEFORE UPDATE OR DELETE ON public.oghma_catalogs
FOR EACH ROW EXECUTE FUNCTION public.oghma_catalog_identity_immutable();

CREATE TABLE public.oghma_catalog_events (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    event_type text NOT NULL CHECK (event_type IN ('import', 'activate', 'rollback', 'classify')),
    catalog_version text REFERENCES public.oghma_catalogs(catalog_version),
    previous_catalog_version text,
    details jsonb NOT NULL DEFAULT '{}'::jsonb
);

CREATE TABLE public.oghma_factory_overrides (
    topic text PRIMARY KEY,
    action text NOT NULL CHECK (action = 'hide'),
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE public.oghma
    ADD COLUMN source_type text,
    ADD COLUMN source_catalog_version text,
    ADD COLUMN source_checksum character(64),
    ADD COLUMN created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ADD COLUMN updated_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP;

UPDATE public.oghma SET source_type = 'legacy' WHERE source_type IS NULL;

ALTER TABLE public.oghma
    ALTER COLUMN source_type SET DEFAULT 'custom',
    ALTER COLUMN source_type SET NOT NULL,
    ADD CONSTRAINT oghma_source_type_check CHECK (source_type IN ('factory', 'custom', 'legacy')),
    ADD CONSTRAINT oghma_source_catalog_fk FOREIGN KEY (source_catalog_version)
        REFERENCES public.oghma_catalogs(catalog_version);

CREATE INDEX oghma_source_type_idx ON public.oghma(source_type);
CREATE INDEX oghma_source_catalog_version_idx ON public.oghma(source_catalog_version);

CREATE TABLE public.oghma_audit (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    contract_version text NOT NULL,
    request_type text NOT NULL DEFAULT '',
    input text NOT NULL DEFAULT '',
    status text NOT NULL,
    grounded jsonb NOT NULL DEFAULT '{}'::jsonb,
    access jsonb NOT NULL DEFAULT '[]'::jsonb,
    fallback jsonb NOT NULL DEFAULT '{}'::jsonb,
    settings jsonb NOT NULL DEFAULT '{}'::jsonb,
    catalog_version text,
    catalog_manifest_sha256 character(64),
    latency_ms double precision NOT NULL DEFAULT 0,
    prompt_sha256 character(64)
);

CREATE INDEX oghma_audit_created_at_idx ON public.oghma_audit(created_at DESC);
CREATE INDEX oghma_audit_status_idx ON public.oghma_audit(status, created_at DESC);

INSERT INTO public.general_settings (id, value, description, updated_at) VALUES
    ('OGHMA_RESULT_LIMIT', '3', 'Maximum Oghma articles included in one prompt after forced and conversational selection.', CURRENT_TIMESTAMP),
    ('OGHMA_EXTRACTOR_TIMEOUT_MS', '1500', 'Hard timeout in milliseconds for the optional Oghma connector fallback.', CURRENT_TIMESTAMP)
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.general_settings (id, value, description, updated_at)
SELECT 'OGHMA_EXTRACTOR_FALLBACK',
       COALESCE((SELECT value FROM public.general_settings WHERE id = 'OGHMA_CUSTOM'), 'false'),
       'Allow one bounded connector fallback for explicit unresolved Oghma requests.',
       CURRENT_TIMESTAMP
ON CONFLICT (id) DO NOTHING;
