<?php

class ImportRules {
    private $table = "import_rules";
    private $db;

    public function __construct() {
        $this->db = $GLOBALS["db"];
    }

    // Create (Insert)
    public function create($data) {
        $fields = [
            "description",
            "match_name",
            "match_race",
            "match_gender",
            "match_base",
            "match_faction",
            "match_mods",
            "action",
            "profile",
            "priority",
            "enabled"
        ];

        $filtered = array_intersect_key($data, array_flip($fields));

        // Separate handling for match_mods because parameterized array assignment needs explicit literal
        $modsLiteral = null;
        if (array_key_exists('match_mods', $filtered)) {
            if (is_array($filtered['match_mods'])) {
                $modsLiteral = $this->toPgArray($filtered['match_mods']);
            } elseif (is_string($filtered['match_mods'])) {
                $vals = array_filter(array_map('trim', explode(',', $filtered['match_mods'])), function($v){ return $v !== ''; });
                $modsLiteral = empty($vals) ? null : $this->toPgArray($vals);
            }
            unset($filtered['match_mods']);
        }

        // Handle JSON for action
        if (isset($filtered['action']) && is_array($filtered['action'])) {
            $filtered['action'] = json_encode($filtered['action'], JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE);
        }

        if (isset($filtered["enabled"]) && $filtered["enabled"]) {
            $filtered["enabled"]="TRUE";
        } else
            $filtered["enabled"]="FALSE";


        // Insert base fields
        $this->db->insert($this->table, $filtered);

        // Set match_mods if provided
        if ($modsLiteral !== null) {
            $row = $this->db->fetchOne("SELECT id FROM {$this->table} ORDER BY id DESC LIMIT 1");
            if ($row && isset($row['id'])) {
                $id = (int)$row['id'];
                $modsSql = ($modsLiteral === null) ? 'NULL' : ("'" . $this->db->escape($modsLiteral) . "'::text[]");
                $sql = "UPDATE {$this->table} SET match_mods = {$modsSql} WHERE id = {$id}";
                $this->db->execQuery($sql);
            }
        }

        return true;
    }

    // Read by ID
    public function getById($id) {
        $id = (int)$id;
        $query = "SELECT * FROM {$this->table} WHERE id = $id LIMIT 1";
        return $this->db->fetchOne($query);
    }

    // Read all (optional WHERE clause)
    public function getAll($where = "TRUE", $orderBy = "priority DESC, id DESC") {
        $query = "SELECT * FROM {$this->table} WHERE $where ORDER BY $orderBy";
        return $this->db->fetchAll($query);
    }

    /**
     * Build the exact-match PostgreSQL regex used by the simple rule editor.
     *
     * @param array $values
     * @return string|null
     */
    public static function buildExactRegex(array $values) {
        $clean = [];
        foreach ($values as $value) {
            $value = trim((string)$value);
            if ($value === '' || in_array($value, $clean, true)) {
                continue;
            }

            $clean[] = preg_replace_callback(
                '/[\\\\.^$|()\[\]{}*+?]/u',
                static function ($match) {
                    return '\\' . $match[0];
                },
                $value
            );
        }

        return empty($clean) ? null : '^(?:' . implode('|', $clean) . ')$';
    }

    /**
     * Decode only regexes generated by buildExactRegex().
     *
     * An empty matcher returns an empty array. A custom regex returns null so
     * the UI can preserve it in Advanced Rules instead of guessing.
     *
     * @param mixed $regex
     * @return array|null
     */
    public static function parseExactRegex($regex) {
        if ($regex === null || trim((string)$regex) === '') {
            return [];
        }

        $regex = (string)$regex;
        if (substr($regex, 0, 4) !== '^(?:' || substr($regex, -2) !== ')$') {
            return null;
        }

        $body = substr($regex, 4, -2);
        $values = [];
        $current = '';
        $escaped = false;
        $length = strlen($body);

        for ($i = 0; $i < $length; $i++) {
            $char = $body[$i];
            if ($escaped) {
                $current .= $char;
                $escaped = false;
                continue;
            }
            if ($char === '\\') {
                $escaped = true;
                continue;
            }
            if ($char === '|') {
                $values[] = $current;
                $current = '';
                continue;
            }
            if (strpos('.^$()[]{}*+?', $char) !== false) {
                return null;
            }
            $current .= $char;
        }

        if ($escaped) {
            return null;
        }

        $values[] = $current;
        return array_values(array_filter($values, static function ($value) {
            return $value !== '';
        }));
    }

    /**
     * Return observed NPC values for the simple rule editor.
     *
     * Suggestions are deliberately not authoritative. The UI permits custom
     * entries for mods, factions, and actors that have not been observed yet.
     */
    public function getEditorOptions() {
        $options = [
            'names' => [],
            'races' => [],
            'genders' => [],
            'factions' => [],
            'mods' => [],
        ];

        $rows = $this->db->fetchAll(
            "SELECT npc_name, race, gender, metadata, extended_data
             FROM core_npc_master
             ORDER BY npc_name"
        );

        foreach ($rows as $row) {
            $this->addOption($options['names'], $row['npc_name'] ?? null);
            $this->addOption($options['races'], $row['race'] ?? null);
            $this->addOption($options['genders'], $row['gender'] ?? null);

            $metadata = $this->decodeObject($row['metadata'] ?? null);
            $mods = $metadata['mods'] ?? [];
            if (is_string($mods)) {
                $mods = preg_split('/[#,\r\n]+/', $mods);
            }
            if (is_array($mods)) {
                foreach ($mods as $mod) {
                    if (is_scalar($mod)) {
                        $this->addOption($options['mods'], $mod);
                    }
                }
            }

            $extended = $this->decodeObject($row['extended_data'] ?? null);
            $factions = $extended['factions'] ?? [];
            if (!is_array($factions)) {
                $factions = [];
            }
            foreach ($factions as $faction) {
                if (is_array($faction)) {
                    $this->addOption($options['factions'], $faction['name'] ?? null);
                }
            }
        }

        foreach ($options as &$values) {
            natcasesort($values);
            $values = array_values($values);
        }
        unset($values);

        return $options;
    }

    // Update by ID
    public function update($id, $data) {
        $id = (int)$id;
        $fields = [
            "description",
            "match_name",
            "match_race",
            "match_gender",
            "match_base",
            "match_faction",
            "match_mods",
            "action",
            "profile",
            "priority",
            "enabled"
        ];

        $filtered = array_intersect_key($data, array_flip($fields));

        // Prepare match_mods literal separately and remove from parameterized update
        $modsLiteral = null;
        $modsProvided = array_key_exists('match_mods', $filtered);
        if ($modsProvided) {
            if (is_array($filtered['match_mods'])) {
                $modsLiteral = $this->toPgArray($filtered['match_mods']);
            } elseif ($filtered['match_mods'] === '' || $filtered['match_mods'] === null) {
                $modsLiteral = null;
            } elseif (is_string($filtered['match_mods'])) {
                $s = trim($filtered['match_mods']);
                if ($s !== '' && $s[0] === '{' && substr($s, -1) === '}') {
                    $modsLiteral = $s;
                } else {
                    $vals = array_filter(array_map('trim', explode(',', $s)), function($v){ return $v !== ''; });
                    $modsLiteral = empty($vals) ? null : $this->toPgArray($vals);
                }
            }
            unset($filtered['match_mods']);
        }

        // Handle JSON for action
        if (isset($filtered['action'])) {
            if (is_array($filtered['action'])) {
                $filtered['action'] = json_encode($filtered['action'], JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE);
            } elseif ($filtered['action'] === '' || $filtered['action'] === null) {
                $filtered['action'] = null;
            }
        }

        if (isset($filtered["enabled"]) && $filtered["enabled"]) {
            $filtered["enabled"]="TRUE";
        } else
            $filtered["enabled"]="FALSE";

        $where = "id = $id";
        $this->db->updateRow($this->table, $filtered, $where);

        if ($modsProvided) {
            $modsSql = ($modsLiteral === null) ? 'NULL' : ("'" . $this->db->escape($modsLiteral) . "'::text[]");
            $sql = "UPDATE {$this->table} SET match_mods = {$modsSql} WHERE id = {$id}";
            $this->db->execQuery($sql);
        }

        return true;
    }

    // Delete by ID
    public function delete($id) {
        $id = (int)$id;
        $where = "id = $id";
        return $this->db->delete($this->table, $where);
    }

    // Truncate the table
    public function truncate($restart = false, $cascade = false) {
        return $this->db->truncate($this->table, $restart, $cascade);
    }

    // Helper to escape strings
    private function escape($str) {
        return $this->db->escape($str);
    }

    private function decodeObject($value) {
        if (is_array($value)) {
            return $value;
        }
        if (!is_string($value) || trim($value) === '') {
            return [];
        }

        $decoded = json_decode($value, true);
        return is_array($decoded) ? $decoded : [];
    }

    private function addOption(array &$values, $value) {
        $value = trim((string)$value);
        if ($value === '' || $value === 'Unknown Faction' || in_array($value, $values, true)) {
            return;
        }
        $values[] = $value;
    }

    private function toPgArray(array $values) {
        $clean = [];
        foreach ($values as $v) {
            if ($v === null) continue;
            $s = trim((string)$v);
            if ($s === '') continue;
            $s = str_replace(['\\', '"'], ['\\\\', '\\"'], $s);
            $clean[] = '"' . $s . '"';
        }
        if (empty($clean)) return null;
        return '{' . implode(',', $clean) . '}';
    }
}

