<!DOCTYPE html>
<html>
<head>
    <link rel="icon" type="image/x-icon" href="images/favicon.ico">
</head>
<body>

<?php

error_reporting(E_ALL);
$enginePath =__DIR__.DIRECTORY_SEPARATOR."..".DIRECTORY_SEPARATOR."..".DIRECTORY_SEPARATOR."..".DIRECTORY_SEPARATOR;

require_once($enginePath . "conf".DIRECTORY_SEPARATOR."conf.php");
require_once($enginePath . "lib" .DIRECTORY_SEPARATOR."model_dynmodel.php");
require_once($enginePath . "lib" .DIRECTORY_SEPARATOR."{$GLOBALS["DBDRIVER"]}.class.php");
require_once($enginePath . "lib" .DIRECTORY_SEPARATOR."data_functions.php");
require_once($enginePath . "lib" .DIRECTORY_SEPARATOR."chat_helper_functions.php");
require_once($enginePath . "lib" .DIRECTORY_SEPARATOR."memory_helper_vectordb.php");
require_once($enginePath . "lib" .DIRECTORY_SEPARATOR."memory_helper_embeddings.php");

echo file_get_contents('template.html');


if ($_SERVER["REQUEST_METHOD"] === "POST") {
    if (isset($_POST["savescript"])) {
        $scriptContent = $_POST["script"];
        file_put_contents('script.json', $scriptContent);
        echo "Script Saved";

    } else if (isset($_POST["runscript"])) {
        sleep(5);
        $output = shell_exec('php HerikaScriptWriter.php');
        echo "<pre>$output</pre>";

    } else if (isset($_POST["savetemplate"])) {
        $scriptContent = $_POST["scriptgenerator"];
        file_put_contents('scriptgenerator.txt', $scriptContent);
        echo "Template Saved";

    } else if (isset($_POST["restoretemplate"])) {
        $scriptgeneratortemplate = file_get_contents('scriptgeneratortemplate.txt');
        file_put_contents('scriptgenerator.txt', $scriptgeneratortemplate);
        echo "Template Restored!";

    } else if (isset($_POST["savegeneratedscript"])) {
        $autogeneratedscript= file_get_contents('autogeneratedscript.json');
        file_put_contents('script.json', $autogeneratedscript);
        echo "Generated Script Saved!";

    } else if (isset($_POST["generatorrun"])) {
        $head[] = array('role' => 'system', 'content' => "Generate a video script following in .json format using these rules.");
        $prompt[] = array('role' => 'user', 'content' => $_POST["scriptgenerator"]);
        
        $contextData=array_merge($head,$prompt);
        $url = $GLOBALS["CONNECTOR"]["openai"]["url"];

        $data = array(
            'model' => (isset($GLOBALS["CONNECTOR"]["openai"]["model"])) ? $GLOBALS["CONNECTOR"]["openai"]["model"] : 'gpt-3.5-turbo-0613',
            'messages' =>
                $contextData
            ,
            'stream' => false,
            'max_tokens'=>$_POST["OPENAI_MAX_TOKENS_MEMORY"]+0,
            'temperature' => ($GLOBALS["CONNECTOR"]["openai"]["temperature"]) ?: 1,
            'presence_penalty' => ($GLOBALS["CONNECTOR"]["openai"]["presence_penalty"]) ?: 1,
            //'response_format'=>'json_object'        
        );

        // Override


        $headers = array(
            'Content-Type: application/json',
            "Authorization: Bearer {$GLOBALS["CONNECTOR"]["openai"]["API_KEY"]}"
        );

        $options = array(
            'http' => array(
                'method' => 'POST',
                'header' => implode("\r\n", $headers),
                'content' => json_encode($data),
                'timeout' => ($GLOBALS["HTTP_TIMEOUT"]) ?: 30
            )
        );

        $context = stream_context_create($options);
        $result = file_get_contents($url, false,$context);

        $data = json_decode($result, true);

        if ($data !== null && isset($data['choices'][0]['message']['content'])) {
            $generatedcontent = $data['choices'][0]['message']['content'];
        } else {
            echo "Failed to extract content from JSON data.";
        }
        file_put_contents('autogeneratedscript.json', $generatedcontent);
        echo "Script Generated! Scroll down to see!";

        
    }
}

$scriptjson = trim(file_get_contents('script.json'));
$scriptgenerator = file_get_contents('scriptgenerator.txt');
$scriptgeneratortemplate = file_get_contents('scriptgeneratortemplate.txt');

echo "
<form action='' method='post'>
<h1>Herika Script Writer ✒</h1>
<h2>Script</h2>
<p>Script needs to be in this exact formating style to work</p>
<textarea name='script' style='width:90%;height:500px'>
$scriptjson
</textarea>
<br>
<input type='submit' name='savescript' value='Save Script' />
<input type='submit' name='runscript' value='Run Script' />

<div class='divider'></div>

<h2>Script Generator Template</h2>
<p>Rules for generating the script.</p>
<textarea name='scriptgenerator' style='width:90%;height:500px'>
$scriptgenerator
</textarea>
<br>
<input type='submit' name='savetemplate' value='Save Template' />
<input type='submit' name='restoretemplate' value='Restore Default Template' />
<h2>Auto Script Generator Output</h2>
<p>Will automatically create a script based on the Script Generator Template.</p>
<textarea name='generatoroutput' style='width:90%;height:300px' placeholder=''>
$generatedcontent
</textarea>
<h3>Token Limit (If generating a long script increase this limit!) </h3>
<p>Using a large token limit can be expensive, you have been warned.</p>
<input type='range' min='400' max='4000' value='".(($_POST["OPENAI_MAX_TOKENS_MEMORY"])?:800)."'  name='OPENAI_MAX_TOKENS_MEMORY' oninput='this.nextElementSibling.value = this.value'>
<output>".(($_POST["OPENAI_MAX_TOKENS_MEMORY"])?:800)."</output>
<br>
<br>
<input type='submit' name='generatorrun' value='Generate Script' />
<input type='submit' name='savegeneratedscript' value='Save Script' />
</form>

</body>
</html>
";

?>
