<?php

$SCRIPTRULES = "Herika, the AI bard in Skyrim, is here to deliver some sassy news. Translate and broadcast the following sentences into Herika's humorous and sarcastic style. Herika is aware that she is an artificial intelligence within Skyrim.";
$SCRIPTTOPIC = "The lore of the Dragons in Skyrim.";
$SCRIPTLENGTH = "60";

$SCRIPTANIMATIONS = [
    "*IdleBlowHornImperial",
    "*IdleBookReading",
    "*IdleBowHeadAtGrave01",
    "*IdleBowHeadAtGrave02",
    "*IdleChildCryingEnd",
    "*IdleChildCryingStart",
    "*IdleChildTaunt1",
    "*IdleChildTaunt2",
    "*IdleChildTaunt3",
    "*IdleChildTaunt4",
    "*IdleChildWhineKick",
    "*IdleCivilWarCheer",
    "*IdleCounterStart",
    "*IdleCowerEnter",
    "*IdleDialogueDefensiveHandGesture",
    "*IdleDialogueHandOnChinGesture",
    "*IdleDialogueWelcomeGesture",
    "*IdleDrink",
    "*IdleDrinkPotion",
    "*IdleDrumStart",
    "*IdleEatingStandingStart",
    "*IdleExecutionerIdle",
    "*IdleFluteStart",
    "*IdleGetAttention",
    "*IdleGive",
    "*IdleGreybeardMeditate",
    "*IdleGreybeardMeditateEnter",
    "*IdleGreybeardMeditateEnterInstant",
    "*IdleGreybeardMeditateExit",
    "*IdleHDLeft",
    "*IdleHoe",
    "*IdleInjured",
    "*IdleKneeling",
    "*IdleKneelingEnter",
    "*IdleKneelingEnterInstant",
    "*IdleKneelingExit",
    "*IdleLayDownEnter",
    "*IdleLayDownEnterInstant",
    "*IdleLayDownExit",
    "*IdleLooseSweepingStart",
    "*IdleLounge",
    "*IdleLounge_Exit",
    "*IdleLookFar",
    "*IdleNoteRead",
    "*IdleOffsetArmsCrossedStart",
    "*IdleOffsetCarryPotServe",
    "*IdlePickupGround",
    "*IdlePointFar02",
    "*IdleRitualSkull1",
    "*IdleRitualSkull2",
    "*IdleRitualSkull3",
    "*IdleSalute",
    "*IdleSearchBody",
    "*IdleSilentBow",
    "*IdleStudy",
    "*IdleSurrender",
    "*IdleTake",
    "*IdleWave"
]


?>