CREATE TABLE IF NOT EXISTS public.chim_harness_run (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL,
    status text NOT NULL DEFAULT 'created',
    mode text NOT NULL DEFAULT 'live',
    scenario text NOT NULL,
    config jsonb NOT NULL DEFAULT '{}'::jsonb,
    snapshot jsonb NOT NULL DEFAULT '{}'::jsonb,
    metrics jsonb NOT NULL DEFAULT '{}'::jsonb,
    error text,
    created_at bigint NOT NULL DEFAULT EXTRACT(EPOCH FROM CURRENT_TIMESTAMP)::bigint,
    started_at bigint,
    ended_at bigint,
    last_tick_at bigint
);

CREATE TABLE IF NOT EXISTS public.chim_harness_actor (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id bigint NOT NULL REFERENCES public.chim_harness_run(id) ON DELETE CASCADE,
    actor_key text NOT NULL,
    actor_name text NOT NULL,
    source text NOT NULL,
    npc_id integer,
    refid varchar(16),
    status text NOT NULL DEFAULT 'pending',
    config jsonb NOT NULL DEFAULT '{}'::jsonb,
    snapshot jsonb NOT NULL DEFAULT '{}'::jsonb,
    metrics jsonb NOT NULL DEFAULT '{}'::jsonb,
    error text,
    created_at bigint NOT NULL DEFAULT EXTRACT(EPOCH FROM CURRENT_TIMESTAMP)::bigint,
    updated_at bigint NOT NULL DEFAULT EXTRACT(EPOCH FROM CURRENT_TIMESTAMP)::bigint,
    UNIQUE (run_id, actor_key)
);

CREATE TABLE IF NOT EXISTS public.chim_harness_event (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id bigint NOT NULL REFERENCES public.chim_harness_run(id) ON DELETE CASCADE,
    actor_id bigint REFERENCES public.chim_harness_actor(id) ON DELETE SET NULL,
    localts bigint NOT NULL DEFAULT EXTRACT(EPOCH FROM CURRENT_TIMESTAMP)::bigint,
    gamets bigint,
    stage text NOT NULL,
    level text NOT NULL DEFAULT 'info',
    message text NOT NULL,
    data jsonb NOT NULL DEFAULT '{}'::jsonb
);

CREATE INDEX IF NOT EXISTS chim_harness_actor_run_status_idx
    ON public.chim_harness_actor (run_id, status);

CREATE INDEX IF NOT EXISTS chim_harness_event_run_localts_idx
    ON public.chim_harness_event (run_id, localts DESC, id DESC);

CREATE UNIQUE INDEX IF NOT EXISTS chim_harness_single_active_run_idx
    ON public.chim_harness_run ((1))
    WHERE status IN ('created', 'preflight', 'provisioning', 'running', 'stopping', 'restoring');

CREATE INDEX IF NOT EXISTS chim_harness_audit_memory_created_at_idx
    ON public.audit_memory (created_at);
