CREATE TABLE IF NOT EXISTS public.core_tts_pronunciation (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_text character varying(120) NOT NULL,
    spoken_text character varying(240) NOT NULL,
    oghma_tags character varying(512) NOT NULL DEFAULT '',
    is_builtin boolean NOT NULL DEFAULT FALSE,
    enabled boolean NOT NULL DEFAULT TRUE,
    created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT core_tts_pronunciation_source_not_blank CHECK (BTRIM(source_text) <> ''),
    CONSTRAINT core_tts_pronunciation_spoken_not_blank CHECK (BTRIM(spoken_text) <> '')
);

CREATE UNIQUE INDEX IF NOT EXISTS core_tts_pronunciation_unique_entry
    ON public.core_tts_pronunciation (LOWER(source_text), LOWER(oghma_tags), is_builtin);
