CREATE TABLE IF NOT EXISTS public.core_tts_fallback (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    race text NOT NULL,
    gender text NOT NULL,
    voiceid text NOT NULL DEFAULT '',
    updated_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT core_tts_fallback_race_gender_key UNIQUE (race, gender),
    CONSTRAINT core_tts_fallback_gender_check CHECK (gender IN ('male', 'female'))
);

INSERT INTO public.core_tts_fallback (race, gender, voiceid)
VALUES
    ('NordRace', 'male', 'malenord'),
    ('NordRace', 'female', 'femalenord'),
    ('ImperialRace', 'male', 'maleeventoned'),
    ('ImperialRace', 'female', 'femaleeventoned'),
    ('BretonRace', 'male', 'maleeventoned'),
    ('BretonRace', 'female', 'femaleeventoned'),
    ('RedguardRace', 'male', 'maleeventonedaccented'),
    ('RedguardRace', 'female', 'femaleeventoned'),
    ('HighElfRace', 'male', 'maleelfhaughty'),
    ('HighElfRace', 'female', 'femaleelfhaughty'),
    ('WoodElfRace', 'male', 'maleyoungeager'),
    ('WoodElfRace', 'female', 'femaleyoungeager'),
    ('DarkElfRace', 'male', 'maledarkelf'),
    ('DarkElfRace', 'female', 'femaledarkelf'),
    ('OrcRace', 'male', 'maleorc'),
    ('OrcRace', 'female', 'femaleorc'),
    ('ArgonianRace', 'male', 'maleargonian'),
    ('ArgonianRace', 'female', 'femaleargonian'),
    ('KhajiitRace', 'male', 'malekhajiit'),
    ('KhajiitRace', 'female', 'femalekhajiit'),
    ('ElderRace', 'male', 'maleoldkindly'),
    ('ElderRace', 'female', 'femaleoldkindly'),
    ('NordRaceChild', 'male', 'malechild'),
    ('NordRaceChild', 'female', 'femalechild'),
    ('ImperialRaceChild', 'male', 'malechild'),
    ('ImperialRaceChild', 'female', 'femalechild'),
    ('BretonRaceChild', 'male', 'malechild'),
    ('BretonRaceChild', 'female', 'femalechild'),
    ('RedguardRaceChild', 'male', 'malechild'),
    ('RedguardRaceChild', 'female', 'femalechild')
ON CONFLICT (race, gender) DO NOTHING;
